### ISSUE TITLE
nbClusters should be between 1 and data size

### ISSUE THREAD

**Issue by Croshiw** [pharo-ai/k-means#10]
This
```st
 | data kmeans |
	data := #( #( 0 0 ) #( 0.5 0 ) #( 0.5 1 ) #( 1 1 ) ).

	kmeans := AIKMeans numberOfClusters: 100.

	kmeans fit: data
```

and this

```st
| data kmeans |
	data := #( #( 0 0 ) #( 0.5 0 ) #( 0.5 1 ) #( 1 1 ) ).
	kmeans := AIKMeans numberOfClusters: -100.
	kmeans fit: data
```
should raise an appropriate exception because now the first one either works or says Tooktoomuchtime while the second raises a SubscriptionOutOfBound

**Comment by jordanmontt** [comment]
We discussed and we need that we should leave this responsibility to the user. Not to check if the number is correct because if we do that we will have to check also the type, is the number is integer, etc...
